### ISSUE TITLE
No font-size defined in headings

### ISSUE THREAD

**Issue by celsomiranda** [corysimmons/typographic#17]
The modular scale is not applied to headings because `font-size` is not defined in any of them.

**Comment by corysimmons** [comment]
Indeed it is applied to them on this line: https://github.com/corysimmons/typographic/blob/master/typographic.styl#L90

![Double Octave](http://i.imgur.com/UXqoXGE.png)

![Minor Second](http://i.imgur.com/U4H3VtL.png)

By not increasing the size of headers by random factors, we just fall back to general default browser sizing for them, which actually looks pretty good, and keeps our file size down a bit.

I'll actually look into this a bit more as it might be throwing vertical rhythm off a bit. Thanks for pointing this out.

**Comment by celsomiranda** [comment]
I'm away from my computer right now, but when I looked at the defaults with 22px max size it didn't look so good.

I think this should be implemented via mixin, because not everyone will need to style the six levels.

Like it is right now, it's not a true&trade; modular scale.

**Comment by corysimmons** [comment]
Went ahead and implemented something. Looks good to me and `$ratio` is definitely a part of the equation.

Fixed https://github.com/corysimmons/typographic/commit/31159cefe62770e29efa375a1d85fe94c1805d43
