### ISSUE TITLE
Vertical Rhythm/Baseline Grid

### ISSUE THREAD

**Issue by jeff-wolff** [corysimmons/typographic#18]
Awesome stuff, thanks for doing this.. I have been meaning to create something similar lately.  Do you have any plans on adding vertical rhythm/some sort of baseline grid?

**Comment by corysimmons** [comment]
It kinda does have a vertical baseline. I wasn't super thorough about it but margins are sized as part of the `line-height`. If you notice something's off with it, let me know.

**Comment by corysimmons** [comment]
Also, thanks for your support. Tell a friend. =)

**Comment by jeff-wolff** [comment]
Yeah I sorta realized after I posted. Nice.

**Comment by corysimmons** [comment]
:+1:
