### ISSUE TITLE
Add vertical rhythm

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/typographic#19]

**Comment by corysimmons** [comment]
Ugh I hate vertical rhythm......... :(

**Comment by corysimmons** [comment]
- [ ] Make responsive
- [ ] Turn into setting
- [ ] Clean up all code

**Comment by celsomiranda** [comment]
:+1:

**Comment by corysimmons** [comment]
@celsomiranda Don't get your hopes up too high, I can't seem to get this... I'm probably going to have to revisit this in the future.

**Comment by corysimmons** [comment]
Backburnering this for 3.0.0 (no idea when that will be).

It's a cool feature, but pretty complicated when so many variables are involved.

**Comment by corysimmons** [comment]
@celsomiranda Get your hopes up again, I just figured this out.

**Comment by corysimmons** [comment]
@celsomiranda :tada: https://github.com/corysimmons/typographic/commit/7b4b66964fdbff07f30c076fc5b368660112eb55

**Comment by celsomiranda** [comment]
Thanks. Will use ASAP!
Em 25/03/2015 06:28, "Cory Simmons" <notifications@github.com> escreveu:

**Comment by corysimmons** [comment]
Awesome, let me know how it works for you and if you like it. Always glad to get real world feedback! :)
