### ISSUE TITLE
Decrease header line-height

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/typographic#30]
And increase `margin-bottom`

**Comment by corysimmons** [comment]
Maintain vertical rhythm

**Comment by flip4bytes** [comment]
Just for reference when you go back and look at it, here's the fix I had come up with. I understand that it messed with the vertical rhythm though. https://github.com/flip4bytes/typographic/commit/0679e617b6afe649a2ae7676edfbd014dfb830e4

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/typographic/commit/1d98aa74bc1dc7afeb9812452811fe5c3f0ad571
