### ISSUE TITLE
Remove Preset Colors

### ISSUE THREAD

**Issue by flip4bytes** [corysimmons/typographic#31]
At the end of the day, typographic should be a tool that helps you manage typography spacing/sizing/etc. And it does all of that BEAUTIFULLY might I add.

The problem is, with a recent release, you went and added things like:

```
a
  color: dodgerblue
    &:visited
      color: darken(dodgerblue, 10%)
```

```
input[type="submit"], button
    background: darken(white, 3%)
```

```
code
    background: darken(white, 2%)
```

```
pre
  padding: vr-block(.5)
  background: darken(white, 2%)
```

```
code
      background: none
```

etc.

You are setting all of those up at the core level which take precedence over any class that we create. This is an absolute nightmare when coding.

You should save all of those base `colors` and `backgrounds` for your [Switch repo](https://github.com/corysimmons/switch) because I really don't think typographic is the right place for it. We should be able to use typographic to get JUST a typography solution but you started embedding a bunch of base colors at the core level into it recently which kind of ruins the purpose of what Typographic is trying to be.

**Comment by corysimmons** [comment]
Fair enough. I had this same question when I was coding them in.

The `a` and `button` have their own browser default colors anyway (that would need to be overriden in a custom design) but I can take out the other colors.

**Comment by flip4bytes** [comment]
Yeah, absolutely. Just please get rid of the:

```
a
    &:visited
      color: darken(dodgerblue, 10%)
```

Color if you REALLY want to keep the `a` color in there though. While yes, the browser kinda has a base visited color set, but when you set `a` with just a basic color then the browser-set `:visited` color stops working.

All I know is that the

```
a
    &:visited
      color: darken(dodgerblue, 10%)
```

Absolutely crippled my site and even when I went to overwrite it, I had to call a global `&:visited` color which then screwed up all of my custom `a` colors. It's just a mess :P

**Comment by corysimmons** [comment]
Not a problem. You're right, this isn't Typographic's job at all and now I have a good excuse to remove them.

Fixed https://github.com/corysimmons/typographic/commit/dca6530e058d62368fe484bceadd18737fe5bf71
