### ISSUE TITLE
Why not change some components into mixins?

### ISSUE THREAD

**Issue by celsomiranda** [corysimmons/typographic#34]
This way we could do:

``` stylus
// Style default components
typographic()

// Style a specific h2 as a paragraph
.site-description
    p()
```

**Comment by corysimmons** [comment]
This is a great idea. :+1:

**Comment by celsomiranda** [comment]
Thank you. This will avoid a hell lot of copy pasting.

**Comment by corysimmons** [comment]
@celsomiranda Is this what you had in mind? It won't reset font-sizes as I expected them to be inherited but maybe I should add that in for your use case?

**Comment by celsomiranda** [comment]
Yes, that was what I had in mind.

Updating and testing as we speak. Thanks!

2015-03-31 1:32 GMT+01:00 Cory Simmons <notifications@github.com>:

**Comment by celsomiranda** [comment]
Works just like I wanted.

Thanks again! :+1:

**Comment by corysimmons** [comment]
I basically pulled everything that was more than one line out into a mixin. Everything that is just one line I didn't think needed it.

Re: my concern about font-sizes

If you use `t-html()` it should reset font sizes, but "t-html" isn't really descriptive of this. Maybe I should make another mixin called `t-p()` that does the same thing as `t-html()`.

**Comment by celsomiranda** [comment]
I don't know if that is really necessary.

I actually used t-h6() for what I needed. And it seem to work fine. (I did
have to reset the font-wheight, color and family however).

2015-03-31 1:41 GMT+01:00 Cory Simmons <notifications@github.com>:

**Comment by corysimmons** [comment]
> I don't know if that is really necessary.

:+1: 

> (I did
have to reset the font-wheight, color and family however).

I could make something like `t-h6(reset)` that would just do the `font-size`, but then I'm curious what else I could reset other than headers?

**Comment by corysimmons** [comment]
Actually, why did you have to reset the `font-weight` `color` and `family`?

It should be the defaults, and if you want to make it look like all the other headers, use `t-header()` as well as `t-h6()`.

**Comment by corysimmons** [comment]
So...

```scss
// Just the font size
p {
  @include t-h6;
}

// The font size and the other attributes of headers
p {
  @include t-header;
  @include t-h6;
}
```

**Comment by celsomiranda** [comment]
I was styling an h2 to look like a paragraph. So calling t-h6() was not giving it the $body-font, etc...

The heading in case was a site description to be used near the title, and although I think it's semanticly an h2, i wanted it to look like a paragraph.

**Comment by corysimmons** [comment]
```scss
h2 {
  @include t-html;
}
```

Should get you what you want without having to manually override anything.

**Comment by corysimmons** [comment]
(this is what I was saying it might be more readable if `t-p()` existed as an alias to `t-html()`

**Comment by celsomiranda** [comment]
Oh, I see. My bad.

Yes, there should definitely be an alias in that case. Actually, Why not just call `t-html()` `t-p()`?

**Comment by corysimmons** [comment]
Added a `t-p()` alias for `t-html()`. Enjoy!

**Comment by corysimmons** [comment]
`t-html()` does a global reset to items that aren't just `p` tags so I wanted to name it something resembling that. Aliasing was built for this purpose though so `t-p()` should be fine.

**Comment by celsomiranda** [comment]
Thanks :+1: 

This project really seems to be eating through versions numbers, eh?

**Comment by corysimmons** [comment]
I'm not great at semver, and I suspect if I was, all of my projects would be at v50 or something by now.

I'm a big fan of iteration if it means the quality of the project goes up. But I tell everyone they should do a hard version lock on all of my projects because I suck at semver.
