### ISSUE TITLE
Weird @media behaviour

### ISSUE THREAD

**Issue by wasd171** [corysimmons/typographic#38]
Hey!

I'm trying to use typographic inside media query, but it seems that in this case the settings are not overridden correctly:

```
@media (max-width: 320px)
	$header-font 	= $geneva
	$body-font 		= $geneva
	$body-color		= orange
	typographic()

```
results in

```
@media (max-width: 320px) {
  html {
    font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif';
    font-weight: 300;
    color: #666;
    font-size: 12px;
    line-height: 1.75em;
  }
//more code here
```
As you can see, the font and color remain default.

**Comment by corysimmons** [comment]
Hm. Not sure what's going on exactly. At first glance it seems like that should work.

Also, sorry I didn't get to this sooner. I keep checking these email notifications on my stupid phone then forgetting to reply to them when I'm near a computer. :(

**Comment by corysimmons** [comment]
Sorry it's taken me so long to respond. I have my ups and downs with being a good maintainer.

I'm planning on migrating this project to PostCSS in the next month or so, and when I do, I'll probably rewrite it from scratch.

---

TBH, I'm not really sure what's going on, but as I said above, this is getting completely rewritten in PostCSS so I think it's safe to close this.
