### ISSUE TITLE
Modify $max-width variable to be consistent with Lost Grid

### ISSUE THREAD

**Issue by flip4bytes** [corysimmons/typographic#39]
Since Lost Grid now utilizes a [`max-width` of `1140px`](https://github.com/corysimmons/lost/blob/master/stylus/lost.styl#L76), might aswell update typographic to coincide with the `$max-width` variable just for consistency sake.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/typographic/commit/64eab0f97b8be5be671ef0af35c557d6a051f7d3
