### ISSUE TITLE
Style more input types with t-input

### ISSUE THREAD

**Issue by mestaritonttu** [corysimmons/typographic#40]
I was going to add some types and make a PR, but then I realized I wasn't sure what should be left unstyled.
http://www.quirksmode.org/html5/inputs/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input

Perhaps number, range, search, tel and url could be included?
Date and time types should offer a datepicker according to spec.. but maybe they should still get styled?

**Comment by corysimmons** [comment]
:+1: Will do this when I get some time this week.

**Comment by prisis** [comment]
Hey :), can I help somehow?

**Comment by corysimmons** [comment]
Sorry, feel free to help but I really need to look at alternative ways to generate a vertical rhythm. The current implementation is borked.

**Comment by corysimmons** [comment]
Sorry it's taken me so long to respond. I have my ups and downs with being a good maintainer.

I'm planning on migrating this project to PostCSS in the next month or so, and when I do, I'll probably rewrite it from scratch.

---

After thinking about this for a little bit, I'm not sure I want to offer any styling to inputs in the new version. I can easily imagine someone adding Typographic to a project and being like "Wtf? Why did my inputs all just change size? Ahh! This stupid _typography_ plugin is messing with my UI kit!"
