### ISSUE TITLE
Does not work with wiredep

### ISSUE THREAD

**Issue by brettdorrans** [corysimmons/typographic#41]
Typographic (specifically the scss version) is not automatically injected by wiredep like your other project, lost.

I suspect this is an issue with the bower.json configuration, but I've not had a chance to look at it in depth. It's a minor annoyance but should probably be fixed!

**Comment by corysimmons** [comment]
What do you mean it's not automatically injected by wiredep?

**Comment by brettdorrans** [comment]
Hey Cory,

Here's the setup I'm using:

I am using the gulp-generator-webapp yeoman generator, which will automatically inject bower dependencies into your project using wiredep. 

When running the following command for your grid project, for example, it will automatically import the scss file into main.scss: 'bower install --save lost'.

Doing the same command for typographic does not work, it is installed by bower, but is not detected by wiredep. Usually this is caused by a malformed bower.json (usually a missing main file declaration).

Cheers.

**Comment by corysimmons** [comment]
Should be fixed now. Let me know. Thanks for filing an issue. :)
