### ISSUE TITLE
Color definitions

### ISSUE THREAD

**Issue by FranzSkuffka** [corysimmons/typographic#45]
Do color definitions really belong into a typographic toolset? I am having conflicts with the reset and normalization included with axis.

**Comment by corysimmons** [comment]
Sorry it's taken me so long to respond. I have my ups and downs with being a good maintainer.

I'm planning on migrating this project to PostCSS in the next month or so, and when I do, I'll probably rewrite it from scratch.

---

Typographic only controls header colors and body colors, but you definitely make a good point that colors shouldn't be set by default.

**Comment by FranzSkuffka** [comment]
nice.  Did you see the pull request?

**Comment by corysimmons** [comment]
I do now. Let's talk about it over there.
