### ISSUE TITLE
Consider upgrading the demo: fonts extremely small on mobile

### ISSUE THREAD

**Issue by ganar** [corysimmons/typographic#52]
I tested the demo this morning but the results on a mobile are lackluster: please check this out.

![img_0352](https://cloud.githubusercontent.com/assets/431185/15934528/ea03eb02-2e31-11e6-84e4-d3681c4e23f3.JPG)

**Comment by corysimmons** [comment]
How is it lackluster?

**Comment by corysimmons** [comment]
Oh, sorry, just saw title.

You can adjust the minimum font size here: https://github.com/corysimmons/typographic/blob/master/scss/typographic.scss#L69

**Comment by ganar** [comment]
Sure: I can see that, I checked out the code before writing this. The demo would be much better if the text could be read on mobile.

**Comment by corysimmons** [comment]
No problem. Feel free to submit a PR to the demo (gh-pages branch I think) and I'll merge it.
