### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/typographic#54]
Leaving GitHub. Looking for maintainer.

@FranzSkuffka 
@larsenwork
@tunnckoCore
@seaneking

**Comment by tunnckoCore** [comment]
Sad to hear, you did awesome work. :)

As about maintaining, I'm not so css guy and not using it, so I can't maintain that.

edit: it would be good to push your refactor/work which you mention you did.

**Comment by larsenwork** [comment]
Hope everything is okay :) 

I'm currently way behind on maintaining my own GitHub projects but I've recently changed job so I have a lot more spare time, so ping me again if nobody else jumps up.

**Comment by janwirth** [comment]
I barely use stylus these days. I do not think I can contribute the time and effort this project deserves. Thank you for considering me though :)

Is there a particular reason you are leaving GitHub? Having an avid open-sourcerer like you leave reminds me of the Heather Arthur leaving the community. Maybe you want to transfer your project to an organisation? I can not maintain the code but I would contribute to administration and moderation :)

https://github.com/harthur-org

**Comment by 2metres** [comment]
I've used this lib regularly for Sass projects, are you still looking for a maintainer. 

Also you opened this issue on my birthday… coincidence?

**Comment by corysimmons** [comment]
@2metres Thanks, transferred. Confirm https://www.npmjs.com/~2metres is you and I'll add you to npm as well.

**Comment by 2metres** [comment]
@corysimmons sorry, I was offline over the weekend. Can you please send another transfer request as the original one has expired

I'm [~2metres](https://www.npmjs.com/~2metres) on npm as well

**Comment by corysimmons** [comment]
@2metres Re-initiated the transfer
