### ISSUE TITLE
html font-size: 62.5%

### ISSUE THREAD

**Issue by simondoescode** [corysimmons/typographic#55]
Slightly confused how I would go about making sure the html is set to 62.5% using your plugin.

**Comment by corysimmons** [comment]
https://github.com/corysimmons/typographic/blob/master/scss/typographic.scss#L594

Uses `t-html()` mixin.

https://github.com/corysimmons/typographic/blob/master/scss/typographic.scss#L251

Is where it sets font size.

https://github.com/corysimmons/typographic/blob/master/scss/typographic.scss#L69

`$min-font` defined.

So just change `$min-font` and `$max-font` to what you want.

I can't guarantee the plugin will still work (as it does some [crazy calc stuff](https://github.com/corysimmons/typographic/blob/master/scss/typographic.scss#L255) and I'm not sure % units will work nicely in [that formula](https://madebymike.com.au/writing/precise-control-responsive-typography/)).

I should also mention this plugin is really old and unmaintained.

Personally, I'm very [lazy](https://webdesign.tutsplus.com/tutorials/the-lazy-persons-guide-to-responsive-typography--cms-22822) and [specific](https://benfrain.com/just-use-pixels/) about responsive typography nowadays. It's much easier to reason about, and you can spend more of your time on bigger design wins.

Best of luck.
